exclude: "^/migrations/"
default_stages: [commit]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

      - id: check-added-large-files
      - id: fix-byte-order-marker #  Запрещает файлы, у которых есть маркер порядка байтов utf-8.
      - id: check-yaml # Проверяет файлы yaml на наличие разбираемого синтаксиса.
      - id: check-json # Устанавливает стандарт для форматирования файлов json.
      - id: check-toml # Проверяет toml-файлы на предмет разбираемого синтаксиса.
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first

      - id: detect-private-key # Определяет наличие закрытых ключей.

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff

  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
