x-base-build: &x-base-build
  image: pottery-cms-instance
  build:
    context: .
    dockerfile: docker/local/instance.dockerfile
  env_file: .env
  volumes:
    - ./config:/opt/pottery/config:z
    - ./pottery:/opt/pottery/pottery:z
  stdin_open: true
  tty: true

services:
  instance:
    <<: *x-base-build
    container_name: pottery-cms-instance
    depends_on:
      - init
    command:
      - /bin/sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G

  init:
    <<: *x-base-build
    container_name: pottery-init
    depends_on:
      - dbms
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py collectstatic --no-input
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  dbms:
    hostname: postgres
    image: postgres:16-alpine
    container_name: dbms
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME?Set DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    command:
        - postgres
        - -c
        - max_connections=100
        - -c
        - shared_buffers=512MB
        - -c
        - work_mem=16MB
        - -c
        - maintenance_work_mem=256MB
        - -c
        - autovacuum_work_mem=128MB
        - -c
        - max_worker_processes=1
        - -c
        - max_parallel_workers_per_gather=4
        - -c
        - max_parallel_workers=1
        - -c
        - checkpoint_timeout=30min
        - -c
        - checkpoint_completion_target=0.9
        - -c
        - max_wal_size=2GB
        - -c
        - min_wal_size=1GB
        - -c
        - random_page_cost=1.2
        - -c
        - effective_cache_size=2GB
        - -c
        - statement_timeout=60s
        - -c
        - shared_preload_libraries=pg_stat_statements
        - -c
        - pg_stat_statements.max=10000
        - -c
        - pg_stat_statements.track=all
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', "${DB_USER}", -d, "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  node:
    build:
      context: .
      dockerfile: docker/local/node.dockerfile
    image: pottery-cms-static
    container_name: pottery-cms-node
    depends_on:
      - instance
    volumes:
      - .:/opt/pottery:z
      - /opt/pottery/node_modules
    command: npm run dev
    ports:
      - '3000:3000'

volumes:
  db-data:
