# Generated by Django 5.0.7 on 2024-07-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная запись?')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная запись?')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='streets', to='organization.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'db_table': 'street',
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Filiation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная запись?')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('is_franchise', models.BooleanField(default=False, verbose_name='Франшиза?')),
                ('street', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                 related_name='filial', to='organization.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'db_table': 'filiation',
            },
        ),
    ]
