# Generated by Django 5.0.7 on 2024-07-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updating datetime')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updating datetime')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='streets', to='organization.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
                'db_table': 'street',
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Filiation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updating datetime')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('is_franchise', models.BooleanField(default=False, verbose_name='Franchise?')),
                ('street', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                 related_name='filial', to='organization.street', verbose_name='Street')),
            ],
            options={
                'verbose_name': 'Filiation',
                'verbose_name_plural': 'Filiations',
                'db_table': 'filiation',
            },
        ),
    ]
