# Generated by Django 5.0.7 on 2024-07-17 12:20

import django.contrib.postgres.indexes
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updating datetime')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('path', models.CharField(max_length=248, verbose_name='Path to file')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updating datetime')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('visits', models.SmallIntegerField(verbose_name='Visits count')),
            ],
            options={
                'verbose_name': 'Master class program',
                'verbose_name_plural': 'Master class programs',
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updating datetime')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(
                    max_length=128, region=None, unique=True, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
                'indexes': [django.contrib.postgres.indexes.HashIndex(fields=['phone_number'], name='client__phone__hash_index'), django.contrib.postgres.indexes.HashIndex(fields=['first_name'], name='client__first_name__hash_index')],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updating datetime')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='client_records', to='master_class.client', verbose_name='Enrolled client')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='master_records', to=settings.AUTH_USER_MODEL, verbose_name='Selected master')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_records',
                 to='master_class.program', verbose_name='Selected master class program')),
            ],
            options={
                'verbose_name': 'Master class record',
                'verbose_name_plural': 'Master class records',
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updating datetime')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('records', models.ManyToManyField(related_name='visits',
                 to='master_class.record', verbose_name='Visit records')),
            ],
            options={
                'verbose_name': 'Master class visit',
                'verbose_name_plural': 'Master class visits',
                'db_table': 'visit',
            },
        ),
        migrations.CreateModel(
            name='WorkPiece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updating datetime')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active?')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('READY', 'Ready'), ('GIVEN', 'Given'), ('OVERDUE', 'Overdue'), (
                    'BROKEN', 'Broken'), ('REPEAT_VISIT', 'Repeat visit')], default='NEW', max_length=16, verbose_name='Workpiece progress status')),
                ('is_glazed', models.BooleanField(default=False, verbose_name='Glazed?')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Expire date')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                 related_name='client_workpieces', to='master_class.client', verbose_name='Client')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                 related_name='master_workpieces', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                 related_name='workpiece', to='master_class.photo', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Workpiece',
                'verbose_name_plural': 'Workpieces',
                'db_table': 'workpiece',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='work_pieces',
            field=models.ManyToManyField(blank=True, related_name='records',
                                         to='master_class.workpiece', verbose_name='Record workpieces'),
        ),
        migrations.AddIndex(
            model_name='workpiece',
            index=django.contrib.postgres.indexes.HashIndex(fields=['status'], name='work_piece__status__hash_index'),
        ),
    ]
