# Generated by Django 5.0.7 on 2024-07-16 13:31

import django.contrib.postgres.indexes
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная запись?')),
                ('path', models.CharField(max_length=248, verbose_name='Путь к фото')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная запись?')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('visits', models.SmallIntegerField(verbose_name='Количество посещений')),
            ],
            options={
                'verbose_name': 'Программа мастер-класса',
                'verbose_name_plural': 'Программы мастер-классов',
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная запись?')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(
                    max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
                'indexes': [django.contrib.postgres.indexes.HashIndex(fields=['phone_number'], name='client__phone__hash_index'), django.contrib.postgres.indexes.HashIndex(fields=['first_name'], name='client__first_name__hash_index')],
            },
        ),
        migrations.CreateModel(
            name='WorkPiece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная запись?')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В работе'), ('READY', 'Готово'), ('GIVEN', 'Отдано'), (
                    'OVERDUE', 'Просрочено'), ('BROKEN', 'Брак'), ('REPEAT_VISIT', 'Повторный визит')], default='NEW', max_length=16, verbose_name='Статус изделия')),
                ('is_glazed', models.BooleanField(default=False, verbose_name='Покрыто глазурью')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата просрочки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='work_pieces', to='master_class.photo')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'db_table': 'work_piece',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная запись?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='client_visits', to='master_class.client')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='master_visits', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='program_visits', to='master_class.program')),
                ('work_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                 related_name='work_piece_visits', to='master_class.workpiece')),
            ],
            options={
                'verbose_name': 'Визит мастер-класса',
                'verbose_name_plural': 'Визиты мастер-классов',
                'db_table': 'visit',
            },
        ),
        migrations.AddIndex(
            model_name='workpiece',
            index=django.contrib.postgres.indexes.HashIndex(fields=['status'], name='work_piece__status__hash_index'),
        ),
    ]
