# Generated by Django 5.0.7 on 2024-07-23 13:32

import pottery.master_class.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to=pottery.master_class.models._upload_to, verbose_name='Path to file'),
        ),
    ]
