# Generated by Django 5.0.7 on 2024-07-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=248, null=True, verbose_name='User photo'),
        ),
    ]
