# Generated by Django 5.0.7 on 2024-07-23 13:32

import pottery.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True,
                                    upload_to=pottery.account.models._upload_to, verbose_name='User photo'),
        ),
    ]
